apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: security
  name: genai-scanner-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: genai-scanner-rolebinding
  namespace: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: genai-scanner-role
subjects:
  - kind: ServiceAccount
    name: scanner-sa
    namespace: security
